/**
 * Default configuration values for Layer 2 application components.
 * These provide sensible starting points so users can start designing
 * without needing deep Kubernetes knowledge.
 */
import type { AppComponentConfigMap, AppComponentType } from "@/domain/entities/app-component";

type AppDefaultsMap = {
  [K in AppComponentType]: AppComponentConfigMap[K];
};

export const APP_COMPONENT_DEFAULTS: AppDefaultsMap = {
  microservice: {
    replicas: 2,
    cpu: "250m",
    memory: "256Mi",
    port: 8080,
    image: "",
    namespace: "default",
    healthCheckPath: "/health",
    readinessPath: "/ready",
    minReplicas: 1,
    maxReplicas: 5,
    targetCPUPercent: 70,
    targetMemoryPercent: 80,
    serviceType: "ClusterIP",
    restartPolicy: "Always",
    environmentVars: 0,
    volumeMounts: 0,
  },
  worker: {
    replicas: 1,
    concurrency: 5,
    memory: "256Mi",
    cpu: "250m",
    image: "",
    namespace: "default",
    restartPolicy: "Always",
    queueBinding: "",
  },
  consumer: {
    groupId: "consumer-group",
    topics: [],
    batchSize: 100,
    autoCommit: true,
    replicas: 1,
    memory: "256Mi",
    cpu: "250m",
    image: "",
    namespace: "default",
    offsetReset: "latest",
    maxPollRecords: 500,
  },
  producer: {
    topics: [],
    serializationFormat: "json",
    batchSize: 16384,
    lingerMs: 5,
    acks: "all",
    replicas: 1,
    memory: "256Mi",
    cpu: "250m",
    image: "",
    namespace: "default",
  },
  api: {
    type: "rest",
    port: 8080,
    rateLimit: 1000,
    replicas: 2,
    memory: "256Mi",
    cpu: "250m",
    image: "",
    namespace: "default",
    healthCheckPath: "/health",
    corsEnabled: true,
    authType: "jwt",
    serviceType: "ClusterIP",
  },
  sidecar: {
    type: "envoy",
    port: 9901,
    protocol: "http",
    memory: "64Mi",
    cpu: "100m",
    image: "",
  },
  "ingress-controller": {
    type: "nginx",
    tls: true,
    hosts: [],
    paths: ["/"],
    replicas: 2,
    memory: "128Mi",
    cpu: "100m",
  },
  cronjob: {
    schedule: "0 * * * *",
    command: "",
    concurrencyPolicy: "Forbid",
    successfulJobsHistoryLimit: 3,
    failedJobsHistoryLimit: 1,
    memory: "256Mi",
    cpu: "250m",
    image: "",
    namespace: "default",
    activeDeadlineSeconds: 600,
  },
  gateway: {
    type: "api-gateway",
    port: 8080,
    replicas: 2,
    rateLimit: 10000,
    memory: "256Mi",
    cpu: "250m",
    image: "",
    namespace: "default",
    corsEnabled: true,
    circuitBreakerEnabled: true,
    retryPolicy: true,
    timeoutMs: 30000,
  },
  "database-client": {
    connectionPoolSize: 10,
    timeoutMs: 5000,
    retryAttempts: 3,
    targetDatabase: "",
  },
  "cache-client": {
    connectionPoolSize: 10,
    timeoutMs: 1000,
    ttlSeconds: 300,
    targetCache: "",
  },
  "batch-processor": {
    batchSize: 1000,
    parallelism: 4,
    memory: "512Mi",
    cpu: "500m",
    image: "",
    namespace: "default",
    retryAttempts: 3,
    timeoutMs: 300000,
  },
};
