name: Build and Deploy React App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install --legacy-peer-deps
        working-directory: ./simulador-arquitetura

      - name: Build do projeto
        run: npm run build
        working-directory: ./simulador-arquitetura

      - name: Enviar arquivos para VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "simulador-arquitetura/build/*"
          target: "/var/www/html"
